platform :ios, '14.0'

install! 'cocoapods',
  :warn_for_unused_master_specs_repo => false

target 'LearnCoreML' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnCoreML
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'LearnCoreMLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnCoreMLUITests' do
    # Pods for testing
  end

end
